#!/usr/bin/python

from systems import Systems

def writeHeader(platform, fileBuffer):
  if platform is Systems.DARWIN.value:
    fileName = '.bash_profile'
  else:
    fileName = '.bashrc'

  headerText = "#!/bin/bash\n# ~/${fileName}: executed by bash(1) for non-login shells.\n# This file was generated by a script. Do not edit manually!\n"
  headerText = headerText.replace("${fileName}", fileName)
  fileBuffer.write(unicode(headerText))
