#!/usr/bin/python

import io

import env

def writeHeader(fileName, fileBuffer):
  fileBuffer.write(unicode("#!/bin/bash\n# " + fileName + ": executed by bash(1) for non-login shells.\n# This file was generated by a script. Do not edit manually!\n"))

def writeInputFileContents(fileName, fileBuffer):
  with open(env.inputFilesDir + fileName) as inputFile:
    print "Compiling " + fileName
    for line in inputFile:
      fileBuffer.write(unicode(line))

def writeOutputFile(filePath, fileBuffer):
  print "Writing output file " + filePath
  with open(filePath, 'w') as outputFile:
    outputFile.write(fileBuffer.getvalue())

def compileBashProfile():
  with io.StringIO() as fileBuffer:
    writeHeader('~/.bash_profile', fileBuffer)
    print "Compiling bash input files..."
    writeInputFileContents('bash_common', fileBuffer)
    writeInputFileContents('bash_mac', fileBuffer)
    writeOutputFile(env.outputFilesDir + 'bash_profile', fileBuffer)
    writeInputFileContents('bash_private', fileBuffer)
    writeOutputFile(env.homeDir + '.bash_profile', fileBuffer)
    print "\nDone."
