#!/bin/bash
# Use this file for aliases that are common across platforms.

goToFirstCol="\[\033[G\]"
green="\[\033[1;32m\]"
blue="\[\033[1;34m\]"
magenta="\[\033[1;35m\]"
default="\[\033[00m\]"
timestamp="[\D{%Y-%m-%d} \t]"

PS1="$goToFirstCol$timestamp $green\u@\h$blue \w"
if [ -f ~/code/scripts/git-prompt.sh ]; then
  source ~/code/scripts/git-prompt.sh
  PS1=$PS1"$magenta$(__git_ps1)"
fi
export PS1=$PS1"$blue\n\$$default "

do_alias() {
  if [ "$(which $2)" != "" ]; then
    alias $1=$2
  fi
}

umask 022

export LS_OPTIONS='-h --color=auto --group-directories-first'
 
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -l'
alias l='ls $LS_OPTIONS -lA'
do_alias "diff" "colordiff"
alias grep='grep --color=auto'
alias dmesg='dmesg -T'

