#!/bin/bash
# ~/.bashrc: executed by bash(1) for non-login shells.
# This file was generated by a script. Do not edit manually!

goToFirstCol="\[\033[G\]"
green="\[\033[1;32m\]"
blue="\[\033[1;34m\]"
magenta="\[\033[1;35m\]"
default="\[\033[00m\]"

PS1="$goToFirstCol$green\u@\h$blue \w"
if [ -f ~/code/scripts/git-prompt.sh ]; then
  source ~/code/scripts/git-prompt.sh
  PS1=$PS1"$magenta$(__git_ps1)"
fi
export PS1=$PS1"$blue \$$default "

umask 022

export LS_OPTIONS='-h --color=auto --group-directories-first'
 
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -l'
alias l='ls $LS_OPTIONS -lA'
alias diff='colordiff'
alias grep='grep --color=auto'
alias dmesg='dmesg -T'

alias pbcopy='xclip -selection c'
alias gimme='sudo apt-get install'
alias remove='sudo apt-get remove'
eval `dircolors`
