#!/bin/bash
# ~/.bashrc: executed by bash(1) for non-login shells.
# This file was generated by a script. Do not edit manually!

export PS1="\[\033[G\]\[\033[01;32m\]\u@\h\[\033[01;34m\] \w\[\033[0;35m\]\$(__git_ps1)\[\033[01;34m\] \$\[\033[00m\] "
umask 022

export LS_OPTIONS='-h --color=auto --group-directories-first'
 
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -l'
alias l='ls $LS_OPTIONS -lA'
alias diff='colordiff'
alias grep='grep --color=auto'
alias dmesg='dmesg -T'

if [ -f ~/code/scripts/git-prompt.sh ]; then
  source ~/code/scripts/git-prompt.sh
fi
alias pbcopy='xclip -selection c'
alias gimme='sudo apt-get install'
alias remove='sudo apt-get remove'
eval `dircolors`
