#!/bin/bash
# Source any commonly used files here.

sourceFile=$(readlink -f ${BASH_SOURCE})
dir=${sourceFile%/*}

if [ -f $dir/bash_private ]; then
  source $dir/bash_private
fi
if [ -f $dir/bash_common ]; then
  source $dir/bash_common
fi
