#!/usr/bin/python
#  install_dotfiles
#  This script will build platform-specific dotfiles and create the appropriate symlinks in ~

import platform
import os

sysName = platform.system()
os.remove('bashrc')
bashrc = open('bashrc','a')
bashrc.write("#!/bin/bash\n")
bashrc.write("# This file was generated by a script. Do not edit manually!\n")

def writeSection(fileName, allowComments):
  f = open(fileName,'r')
  for line in f:
    if line.startswith('#'):
      if allowComments:
        bashrc.write(line)
    else:
      bashrc.write(line)

if sysName == 'Linux':
  bashrc.write("# ~/.bashrc: executed by bash(1) for non-login shells.\n")
  if os.path.isfile('bash_private'):
    writeSection('bash_private',False)
  writeSection('bash_common',False)
  writeSection('bash_linux',True)
elif sysName == 'Darwin':
  bashrc.write("# ~/.bash_profile: executed by bash(1) for lon-login shells.\n")
  writeSection('bash_mac',True)
  if os.path.isfile('bash_private'):
    writeSection('bash_private',False)
  writeSection('bash_common',False)
else:
  print "System not supported!"
  bashrc.close()
  exit(1)
bashrc.close()

